apiVersion: v1
kind: Service
metadata:
  name: telephone-index-load-balancer
  labels:
    app: react-telephone-index
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 80
  selector:
    app: react-telephone-index
