name: Continuois Integration / Continuous Delivery Workflow for TelephoneIndex

on: [push]

jobs:
  Setup-Build-Test-Dockerize-Push:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checking out source code
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Installing dependencies
        run: |
          npm install
          npm ci
          npx playwright install --with-deps
          cd telephone-index
          npm install
          npm ci

      - name: Building
        run: |
          cd telephone-index
          npm run build --if-present

      - name: Unit testing
        env:
          CI: true
        run: |
          npm run build-unit-tests
          npm run unit-tests

      - name: Launching application
        run: |
          cd telephone-index
          npm install -g serve
          serve -s build &

      - name: Acceptance testing
        run: |
          npx playwright test

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Building container image
        run: |
          cd telephone-index
          docker build -t cnlklink/react-telephone-index .

      - name: Pushing to Dockerhub
        run: |
          docker push


