name: Continuois Integration / Continuous Delivery Workflow for TelephoneIndex

on: [push]

jobs:
  Setup-Build-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checking out source code
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Installing dependencies
        run: |
          npm install
          npm ci
          npx playwright install --with-deps
          cd telephone-index
          npm install
          npm ci

      - name: Unit testing
        env:
          CI: true
        run: |
          cd telephone-index
          npm test

      - name: Building
        run: |
          cd telephone-index
          npm run build --if-present

      - name: Launching application
        run: |
          cd telephone-index
          npm install -g serve
          serve -s build &

      - name: Acceptance testing
        run: |
          npx playwright test

