name: Continuois Integration / Continuous Delivery Workflow for TelephoneIndex

on: [push]

jobs:
  Setup-Build-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          npm install
          cd telephone-index
          npm install

      - name: Unit test
        env:
          CI: true
        run: |
          cd telephone-index
          npm test

      - name: Build
        run: |
          cd telephone-index
          npm run build --if-present

      - name: Launch application
        run: |
          cd telephone-index
          npm install -g serve
          serve -s build

      - name: Acceptance test
        run: |
          echo 'TODO: npx playwright test'

