name: Continuois Integration / Continuous Delivery Workflow for TelephoneIndex

on: [push]

jobs:
  Setup-Build-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          npm install
          cd telephone-index
          npm install

      - name: Build
        run: |
          echo 'TODO - build step'

      - name: Unit test
        env:
          CI: true
        run: |
          cd telephone-index
          npm test

      - name: Launch application
        env:
          CI: true
        run: |
          cd telephone-index
          npm start

      - name: Acceptance test
        run: |
          echo 'TODO - acceptance test step'

